AOSCOS: platform/x86: int3472: remove an unused argument to dev_err()
When building with CONFIG_WERROR:

  drivers/platform/x86/intel/int3472/discrete.c:391:47: error: too many arguments for format [-Werror=format-extra-args]
    391 |                         dev_err(int3472->dev, "Failed to register type 0x02x: %d\n", type, ret);
        |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Remove the unused `type' argument to fix build.

Fixes: "BACKPORT: SURFACE: Add camera support for Surface Pro 9"
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>