AOSCOS: drm: cix: drop unused linlondp_gop_set
When building with CONFIG_WERROR, the following error occurs:

  drivers/gpu/drm/cix/linlon-dp/linlondp_dev.c:623:13: error: ‘linlondp_gop_set’ defined but not used [-Werror=unused-function]
  623 | static void linlondp_gop_set(void)
      |             ^~~~~~~~~~~~~~~~

Remove this function to fix build.

Fixes: "CIXTECH: drm: add cix linlon dp driver"
Link: https://github.com/cixtech/cix-linux-main/issues/26
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>