PHYTIUM: net/phytmac:Fix compilation errors caused by disabling CONFIG_ACPI
Disabling CONFIG_ACPI will cause errors like 'error: implicit
declaration of function ‘acpi_evaluate_integer’', so it is necessary
to add #ifdef CONFIG_ACPI for protection.

Signed-off-by: 李桐凤 <litongfeng1497@phytium.com.cn>

Link: https://gitee.com/phytium_embedded/phytium-linux-kernel/commit/966bfbf1d4142f8e2256b082956eed7791e1ff0d
Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>