AOSCOS: typec: add missing include to <linux/irq.h>
Whilst building against 7.0.3, the following error occurs:

  drivers/usb/typec/rts5453.c: In function ‘rts_request_irq_work_fn’:
  drivers/usb/typec/rts5453.c:587:9: error: implicit declaration of function ‘irq_set_status_flags’ [-Wimplicit-function-declaration]
    587 |         irq_set_status_flags(client->irq, IRQ_DISABLE_UNLAZY);
        |         ^~~~~~~~~~~~~~~~~~~~
  drivers/usb/typec/rts5453.c:587:43: error: ‘IRQ_DISABLE_UNLAZY’ undeclared (first use in this function)
    587 |         irq_set_status_flags(client->irq, IRQ_DISABLE_UNLAZY);
        |                                           ^~~~~~~~~~~~~~~~~~

Add a missing include to <linux/irq.h> to fix build.

Link: https://github.com/cixtech/cix-linux-main/issues/14
Fixes: "CIXTECH: typec: add rts5453 driver"
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>